### ISSUE TITLE
Investigate brk

### ISSUE THREAD

**Issue by Danack** [Danack/TodoList#1]
PHP is calling brk -  http://man7.org/linux/man-pages/man2/brk.2.html on every request,

ACTION ITEM! Investigate what is calling it.

This requires an optimised deployment.

**Comment by Danack** [comment]
apparently iotop is the tool to test if it's being caused by vmswapping shenanigans.

**Comment by Danack** [comment]
This is some sample output from strace, which shows that brk() is being called three times.

```
     0.000216 poll([{fd=4, events=POLLIN}], 1, 5000) = 1 ([{fd=4, revents=POLLIN}])
     0.000213 read(4, "\1\1\0\1\0\10\0\0", 8) = 8
     0.000254 read(4, "\0\1\0\0\0\0\0\0", 8) = 8
     0.000171 read(4, "\1\4\0\1\3o\1\0", 8) = 8
     0.000162 read(4, "\f\vQUERY_STRINGstart=12345\17'SCRIP"..., 880) = 880
     0.000177 read(4, "\1\4\0\1\0\0\0\0", 8) = 8
     0.000232 setitimer(ITIMER_PROF, {it_interval={0, 0}, it_value={4, 0}}, NULL) = 0
     0.000208 rt_sigaction(SIGPROF, {0x7faaa0, [PROF], SA_RESTORER|SA_RESTART, 0x7f1d6fa6e920}, {0x7faaa0, [PROF], SA_RESTORER|SA_RESTART, 0x7f1d6fa6e920}, 8) = 0
     0.000210 rt_sigprocmask(SIG_UNBLOCK, [PROF], NULL, 8) = 0
     0.000252 getcwd("/home/github/Blog/Blog/scripts", 4095) = 31
     0.000227 chdir("/home/github/Blog/Blog/public") = 0
     0.000494 setitimer(ITIMER_PROF, {it_interval={0, 0}, it_value={30, 0}}, NULL) = 0
     0.000169 fcntl(3, F_SETLK, {type=F_RDLCK, whence=SEEK_SET, start=1, len=1}) = 0
     0.000214 getcwd("/home/github/Blog/Blog/public", 4096) = 30
*****0.000281 brk(0x33f2000)            = 0x33f2000
*****0.000451 brk(0x3432000)            = 0x3432000
     0.000339 chdir("/home/github/Blog/Blog/scripts") = 0
     0.000386 times({tms_utime=1, tms_stime=5, tms_cutime=0, tms_cstime=0}) = 595818202
     0.000165 setitimer(ITIMER_PROF, {it_interval={0, 0}, it_value={0, 0}}, NULL) = 0
     0.000178 fcntl(3, F_SETLK, {type=F_UNLCK, whence=SEEK_SET, start=0, len=0}) = 0
     0.000234 write(4, "\1\6\0\1\0001\7\0Content-type: text/html;"..., 80) = 80
     0.000204 shutdown(4, SHUT_WR)      = 0
     0.000511 recvfrom(4, "\1\5\0\1\0\0\0\0", 8, 0, NULL, NULL) = 8
     0.000193 recvfrom(4, "", 8, 0, NULL, NULL) = 0
     0.000198 close(4)                  = 0
*****0.000285 brk(0x33b2000)            = 0x33b2000
     0.000221 setitimer(ITIMER_PROF, {it_interval={0, 0}, it_value={0, 0}}, NULL) = 0
     0.000215 accept(0, {sa_family=AF_LOCAL, NULL}, [2]) = 4
     1.580021 times({tms_utime=1, tms_stime=5, tms_cutime=0, tms_cstime=0}) = 595818360
```



These appear to be the 2 places that I could find with GDB where brk() was being called.


```
Breakpoint 1, 0x00007f53b8c2d910 in brk () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f53b8c2d910 in brk () from /lib64/libc.so.6
#1  0x00007f53b8c2d9c5 in sbrk () from /lib64/libc.so.6
#2  0x00007f53b8bca919 in __default_morecore () from /lib64/libc.so.6
#3  0x00007f53b8bc5a02 in _int_free () from /lib64/libc.so.6
#4  0x00000000007e3e30 in zend_mm_shutdown (heap=0x16ff2d0, full_shutdown=<value optimized out>, silent=<value optimized out>)
    at /home/github/BastionRPM/rpmbuild/BUILD/php-5.6.9/Zend/zend_alloc.c:1697
#5  0x00000000007a9fc6 in php_request_shutdown (dummy=<value optimized out>)
    at /home/github/BastionRPM/rpmbuild/BUILD/php-5.6.9/main/main.c:1904
#6  0x00000000008b7b59 in main (argc=<value optimized out>, argv=<value optimized out>)
    at /home/github/BastionRPM/rpmbuild/BUILD/php-5.6.9/sapi/fpm/fpm/fpm_main.c:1992
```

``

Breakpoint 1, 0x00007f53b8c2d910 in brk () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f53b8c2d910 in brk () from /lib64/libc.so.6
#1  0x00007f53b8c2d9c5 in sbrk () from /lib64/libc.so.6
#2  0x00007f53b8bca919 in __default_morecore () from /lib64/libc.so.6
#3  0x00007f53b8bc702a in _int_malloc () from /lib64/libc.so.6
#4  0x00007f53b8bc7911 in malloc () from /lib64/libc.so.6
#5  0x00000000007e3970 in _zend_mm_alloc_int (heap=0x16ff2d0, size=64)
    at /home/github/BastionRPM/rpmbuild/BUILD/php-5.6.9/Zend/zend_alloc.c:1982
#6  0x00000000007e3cf7 in _ecalloc (nmemb=8, size=8) at /home/github/BastionRPM/rpmbuild/BUILD/php-5.6.9/Zend/zend_alloc.c:2610
#7  0x0000000000818984 in _zend_hash_index_update_or_next_insert (ht=0x7f53bd684f68, h=0, pData=0x7fff538955a8, nDataSize=8, pDest=0x0, 
    flag=<value optimized out>) at /home/github/BastionRPM/rpmbuild/BUILD/php-5.6.9/Zend/zend_hash.c:392
#8  0x000000000083bed7 in ZEND_ADD_ARRAY_ELEMENT_SPEC_TMP_UNUSED_HANDLER (execute_data=<value optimized out>)
    at /home/github/BastionRPM/rpmbuild/BUILD/php-5.6.9/Zend/zend_vm_execute.h:11776
#9  0x00000000008779b0 in execute_ex (execute_data=0x7f53bd648d18)
    at /home/github/BastionRPM/rpmbuild/BUILD/php-5.6.9/Zend/zend_vm_execute.h:363
#10 0x0000000000809739 in zend_execute_scripts (type=8, retval=0x0, file_count=3)
    at /home/github/BastionRPM/rpmbuild/BUILD/php-5.6.9/Zend/zend.c:1341
#11 0x00000000007a921a in php_execute_script (primary_file=0x7fff53899e30)
    at /home/github/BastionRPM/rpmbuild/BUILD/php-5.6.9/main/main.c:2597
#12 0x00000000008b8047 in main (argc=<value optimized out>, argv=<value optimized out>)
    at /home/github/BastionRPM/rpmbuild/BUILD/php-5.6.9/sapi/fpm/fpm/fpm_main.c:1964

```

**Comment by Danack** [comment]
PHP is fast enough for me now. Trying to get to less than 5ms response time is not a valid use of my time currently.
